<a href="https://colab.research.google.com/github/Nattakonjpg/BasicProg_DataViz65/blob/main/Data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Dictionary

- คล้าย list ()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นเลขลำดับ
- ลำดับไม่มีความสำคัญ

In [ ]:
dict_a = {1:"Hello",'N':"New",3:"Year",'4':"2022"} # { } Curly brackets


In [ ]:
dict_a[1] # 1:กำหนดให้ตัวนั้นเป็น index 1


In [ ]:
dict_a.keys() #index = keys เรียก check มาดูก่อนว่ามี key ไรบ้าง

In [ ]:
dict_a.values() #ดูว่ามีค่าอะไรบ้างข้างใน

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14 #ระบุ index แล้วก็ค่านั้น

In [ ]:
dict_a['N'] ="Newwwwwwwww"

In [ ]:
dict_a

##Numpy array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [ ]:
import numpy

In [ ]:
list_A=[1,2,3,4,5]

In [ ]:
arr_a =numpy.array(list_A)

In [ ]:
5 * arr_a #5 ไปคูณข้างใน (Scalar multiplication)

In [ ]:
4* list_A # Duplicate 4 รอบ

In [ ]:
arr_b = numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a, arr_b) 

In [ ]:
arr_a+arr_b

### 2D array

In [ ]:
import numpy as np # as np ตั้งให้มันเป็น np

In [ ]:
arr2_z = np.array([[1,2,3],[4,5,6]]) #2 แถว 3หลัก

In [ ]:
arr2_z.shape

#np.zeros()

In [24]:
arr2_3_5_0 =np.zeros((3,5)) ## 3 แถว 5 หลัก

In [ ]:
arr2_3_5_0

In [26]:
arr2_3_5_0[1,2] = 9 #แถว 1 หลัก 2

In [27]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
arr2_3_5_0[1,2]

In [ ]:
print(list_A)
list_A[-1] = "Christmas" #แทนด้วยคำนี้
print(list_A)

#np.ones()

In [30]:
arr2_4_5_1 = np.ones((4,5))

In [ ]:
arr2_4_5_1

In [36]:
arr2_4_5_1[0,0] =9

In [ ]:
arr2_4_5_1

In [38]:
arr2_4_5_200 =200*np.ones((4,4))

In [39]:
arr2_4_5_200

array([[200., 200., 200., 200.],
       [200., 200., 200., 200.],
       [200., 200., 200., 200.],
       [200., 200., 200., 200.]])

#Matrix Operations

**การบวก ลบ Matrix M+-N บวกลบตัวที่อยู่ตำแหน่งเดียวกัน**

#Matrix Slicing

In [48]:
import numpy

In [49]:
mat_a = numpy.array([[2,4,5],[1,2,3],[9,8,7],[3,6,9]])
print(mat_a)

[[2 4 5]
 [1 2 3]
 [9 8 7]
 [3 6 9]]


In [50]:
import numpy as np

In [51]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_b= np.array(list_b)
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz 2
1.slice ค่าลบออกมาจาก '''mat_b'''

2.slice '''[1,2,3] ''' จาก '''mat_a'''

3.slice '''[[1,3], [9,7], [3,9]]''' ออกจาก'''mat_b'''

In [60]:
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [76]:
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

In [68]:
mat_a[1:2,:4]

array([[1, 2, 3]])

In [75]:
mat_b[:5,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [87]:
mat_b[1:,2:5]

array([[1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])