<a href="https://colab.research.google.com/github/Nattakonjpg/BasicProg_DataViz65/blob/main/Data_structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Data Structure (โครงสร้างข้อมูล)
การเก็บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นระเบียบ


##List () 

In [ ]:
list_a =[1,2,3,4,5] #square bracket

In [ ]:
list_b =['ab',1,2,3.14,True,list_a]

In [ ]:
list_b

['ab', 1, 2, 3.14, True, [1, 2, 3, 4, 5]]

### indexing การชี้สมาชิกใน list ด้วยลำดับของ list

In [ ]:
list_b[3]

In [ ]:
list_b[5] #ทั้งก้อน

In [ ]:
list_b[-1] #ตัวสุดท้ายของ list คือ-1 นับถอยไป

###การสร้าง list()

In [ ]:
list_c1 = [] #แบบที่1
list_c2 = list() #แบบที่ 2

In [ ]:
print(list_c1,list_c2)

###เพิ่มสมาชิกเข้าไปใน List ด้วย append()

In [ ]:
list_c1.append("Bank") #เพิ่มข้อความใน c1

###ลบสมาชิกจาก List ด้วย pop()

In [ ]:
list_c1.pop()
print(list_c1)

###Len() ตรวจสอบจำนวนสมาชิกใน List

In [ ]:
print(list_b)
print(len(list_b)) #มีสมาชิก 6ตัว

##String is a list of characters

In [ ]:
st_start = "Department of Statistics, Faculty of Science"

In [ ]:
st_start[9]

In [ ]:
len(st_start) #มีสมาชิก 44 ตัว

##Colon :  [start:stop,step]



In [ ]:
list_a

In [ ]:
list_a[-3:] # : -> colon

In [ ]:
list_a[1:] #เอาตั้งแต่ตัวindex [1]

###Step

In [ ]:
list_c =[1,2,3,4,5,6,7,8,9,10]

In [ ]:
list_c[:9:3] #ตั้งแต่ตัวที่ 1->9 โดยนับทีละ3

In [ ]:
list_c[:10:2] #ตั้งแต่ตัวที่ 1->10 โดยนับทีละ2 

### range()

In [ ]:
range(21) # จะได้ 21 ตัวเริ่มจาก 0

In [ ]:
a = list(range(1,21)) # ได้21 ตัวเริ่มจาก 1

In [ ]:
a

##Dictionary

- คล้าย list ()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นเลขลำดับ
- ลำดับไม่มีความสำคัญ

In [ ]:
dict_a = {1:"Hello",'N':"New",3:"Year",'4':"2022"} # { } Curly brackets


In [ ]:
dict_a[1] # 1:กำหนดให้ตัวนั้นเป็น index 1


In [ ]:
dict_a.keys() #index = keys เรียก check มาดูก่อนว่ามี key ไรบ้าง

In [ ]:
dict_a.values() #ดูว่ามีค่าอะไรบ้างข้างใน

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14 #ระบุ index แล้วก็ค่านั้น

In [ ]:
dict_a['N'] ="Newwwwwwwww"

In [ ]:
dict_a

##Numpy array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [ ]:
import numpy

In [ ]:
list_A=[1,2,3,4,5]

In [ ]:
arr_a =numpy.array(list_A)

In [ ]:
5 * arr_a #5 ไปคูณข้างใน (Scalar multiplication)

In [ ]:
4* list_A # Duplicate 4 รอบ

In [ ]:
arr_b = numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a, arr_b) 

In [ ]:
arr_a+arr_b

### 2D array

In [ ]:
import numpy as np # as np ตั้งชื่อให้มันเป็น np

In [ ]:
arr2_z = np.array([[1,2,3],[4,5,6]]) #array([],[]) ตัวหน้า=จำนวน2 แถว,ตัวหลัง=จำนวน3หลัก สมาชิกย่อยตัวละ3ตัว

In [ ]:
arr2_z.shape #เช็คว่าหลักและแถวมีเท่าไหร่

In [ ]:
arr2_z

#np.zeros()

In [ ]:
arr2_3_5_0 = np.zeros((3,5)) ## 3 แถว 5 หลัก ,np.zero ตัวเลขข้างในจะเป็น 0
arr2_3_5_0

In [ ]:
arr2_3_5_0[1,2] = 9 #แถว 1 หลัก 2 ,แถวหลักจะเริ่มจาก 0,0
arr2_3_5_0

In [ ]:
arr2_3_5_0[1,2] #แถวที่ 1  หลักที่ 2 คือตัวเลข 9

In [ ]:
list_A = [1,2,3,4,5]
print(list_A)
list_A[-1] = "Christmas" #แทนตัวสุดท้าย(5) ด้วยคำนี้
print(list_A)

#np.ones()

In [ ]:
arr2_4_5_1 = np.ones((4,5)) # 3แถว 5 หลัก เต็มไปด้วยเลข 1
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr2_4_5_1[0,0] =9 #ให้ตัวที่อยู่แถว 0 หลัก 0 เป็น 9

In [ ]:
arr2_4_5_1.shape

(4, 5)

In [ ]:
arr2_4_5_200 =200*np.ones((4,5)) #ให้เลขข้างในเป็นเลข 200 แทนเลข 1

In [ ]:
arr2_4_5_200

In [ ]:
arr2_4_5_200.shape

(4, 5)

#Matrix Operations

**การบวก ลบ Matrix $M+-N$ (บวกลบตัวที่อยู่ตำแหน่งเดียวกัน)**

In [ ]:
 arr2_4_5_200 + arr2_3_5_0 # การบวก ลบ matrix shape ต้องเท่ากัน 

In [ ]:
arr2_4_5_200 + arr2_4_5_1 # shape เท่ากัน (4,4)

### การคูณ matrix
 $aM$  scalar คูณ Matrix  (scalar คูณกระจายเข้าไปในทุกตัว)


In [ ]:
5 * arr_a #5 ไปคูณข้างใน (Scalar multiplication)

$M\times N$ Matrix คูณ Matrix (แถวคูณหลัก)
- (m,n) $\times$ (n,o) = (m,o) (Shape) m แถว o หลัก

In [ ]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3],[4,6],[7,9]])

In [ ]:
print(mat_a) # 2 x 3

[[2 4 5]
 [1 2 3]
 [9 8 7]
 [3 6 9]]


In [ ]:
print(mat_b) # 2 x 3

[[ 1  2  5]
 [ 2  4 -7]]


In [ ]:
print(mat_c) # 3 x 2

[[2 3]
 [4 6]
 [7 9]]


axc , bxc

In [ ]:
np.dot(mat_a,mat_c) #คูณกันได้เพราะshapeเท่ากัน, 2x2

array([[ 51,  69],
       [ 81, 111]])

In [ ]:
np.dot(mat_b,mat_c) # 2x 2

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [ ]:
np.dot(mat_c,mat_a)  #3 x 3

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [ ]:
mat_X = np.dot(mat_c,mat_b) #3 x 3

In [ ]:
mat_a * mat_b #คูณแบบไม่ตรงตามเมทริก คูณตรงตามตำแหน่ง ต้องใช้ .dot

array([[  2,   6,  25],
       [  8,  24, -49]])

#Matrix Slicing

In [ ]:
mat_X[:2,:2]

array([[ 8, 16],
       [16, 32]])

In [ ]:
import numpy

In [ ]:
mat_Y = numpy.array([[2,4,5],[1,2,3],[9,8,7],[3,6,9]])
print(mat_Y)

[[2 4 5]
 [1 2 3]
 [9 8 7]
 [3 6 9]]


In [ ]:
import numpy as np

In [ ]:
list_b = [[-1,-1,2,4,5],[-2,-2,1,2,3],[-3,-3,9,8,7],[-4,-4,3,6,9]]
mat_Z= np.array(list_b)
mat_Z

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

## Quiz 2
1.slice ค่าลบออกมาจาก '''mat_b'''

2.slice '''[1,2,3] ''' จาก '''mat_a'''

3.slice '''[[1,3], [9,7], [3,9]]''' ออกจาก'''mat_b'''

In [ ]:
mat_a

array([[2, 4, 5],
       [1, 2, 3],
       [9, 8, 7],
       [3, 6, 9]])

In [ ]:
mat_b

array([[-1, -1,  2,  4,  5],
       [-2, -2,  1,  2,  3],
       [-3, -3,  9,  8,  7],
       [-4, -4,  3,  6,  9]])

In [ ]:
mat_a[1:2,:4]

array([[1, 2, 3]])

In [ ]:
mat_b[:5,:2]

array([[-1, -1],
       [-2, -2],
       [-3, -3],
       [-4, -4]])

In [ ]:
mat_b[1:4,2:5:2]

array([[1, 3],
       [9, 7],
       [3, 9]])