##Dictionary

- คล้าย list ()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นเลขลำดับ
- ลำดับไม่มีความสำคัญ

In [ ]:
dict_a = {1:"Hello",'N':"New",3:"Year",'4':"2022"} # { } Curly brackets


In [ ]:
dict_a[1] # 1:กำหนดให้ตัวนั้นเป็น index 1


In [ ]:
dict_a.keys() #index = keys เรียก check มาดูก่อนว่ามี key ไรบ้าง

In [ ]:
dict_a.values() #ดูว่ามีค่าอะไรบ้างข้างใน

### การเพิ่มสมาชิกลงไปใน Dictionary

In [ ]:
dict_a[7] = 3.14 #ระบุ index แล้วก็ค่านั้น

In [ ]:
dict_a['N'] ="Newwwwwwwww"

In [ ]:
dict_a

##Numpy array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [ ]:
import numpy

In [ ]:
list_A=[1,2,3,4,5]

In [ ]:
arr_a =numpy.array(list_A)

In [ ]:
5 * arr_a #5 ไปคูณข้างใน (Scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [ ]:
4* list_A # Duplicate 4 รอบ

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [ ]:
arr_b = numpy.array([10,20,30,40,50])

In [ ]:
print(arr_a, arr_b) 

[1 2 3 4 5] [10 20 30 40 50]


In [ ]:
arr_a+arr_b

array([11, 22, 33, 44, 55])

### 2D array

In [ ]:
import numpy as np # as np ตั้งให้มันเป็น np

In [ ]:
arr2_z = np.array([[1,2,3],[4,5,6]]) #2 แถว 3หลัก

In [ ]:
arr2_z